spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.tool.schema: debug
