package com.petcare.pet_care.infra.awsConfig;

import feign.RequestInterceptor;
import feign.RequestTemplate;
import software.amazon.awssdk.auth.credentials.AwsCredentialsProvider;
import software.amazon.awssdk.auth.signer.Aws4Signer;
import software.amazon.awssdk.auth.signer.params.Aws4SignerParams;
import software.amazon.awssdk.http.SdkHttpFullRequest;
import software.amazon.awssdk.http.SdkHttpMethod;
import software.amazon.awssdk.regions.Region;

import java.io.ByteArrayInputStream;
import java.net.URI;
import java.util.ArrayList;
import java.util.Collection;

public class SesSigV4RequestInterceptor implements RequestInterceptor {

    private static final String SERVICE_NAME = "ses";
    private final Aws4Signer signer = Aws4Signer.create();
    private final AwsCredentialsProvider credentialsProvider;
    private final Region region;

    public SesSigV4RequestInterceptor(AwsCredentialsProvider credentialsProvider, Region region) {
        this.credentialsProvider = credentialsProvider;
        this.region = region;
    }

    @Override
    public void apply(RequestTemplate template) {
        URI uri = buildUri(template);
        byte[] payload = template.body() != null ? template.body() : new byte[0];

        SdkHttpFullRequest.Builder requestBuilder = SdkHttpFullRequest.builder()
                .method(SdkHttpMethod.fromValue(template.method()))
                .protocol(uri.getScheme())
                .host(uri.getHost())
                .encodedPath(normalizePath(uri.getRawPath()));

        if (uri.getPort() != -1) {
            requestBuilder.port(uri.getPort());
        }

        template.headers().forEach((name, values) -> appendHeaders(requestBuilder, name, values));
        requestBuilder.contentStreamProvider(() -> new ByteArrayInputStream(payload));

        Aws4SignerParams signerParams = Aws4SignerParams.builder()
                .signingName(SERVICE_NAME)
                .signingRegion(region)
                .awsCredentials(credentialsProvider.resolveCredentials())
                .build();

        SdkHttpFullRequest signedRequest = signer.sign(requestBuilder.build(), signerParams);

        // Replace original headers with signed headers generated by AWS SigV4.
        new ArrayList<>(template.headers().keySet()).forEach(template::removeHeader);
        signedRequest.headers().forEach(
                (headerName, values) -> template.header(headerName, values.toArray(new String[0]))
        );
    }

    private void appendHeaders(
            SdkHttpFullRequest.Builder requestBuilder,
            String name,
            Collection<String> values
    ) {
        if ("Content-Length".equalsIgnoreCase(name)) {
            return;
        }
        for (String value : values) {
            requestBuilder.appendHeader(name, value);
        }
    }

    private URI buildUri(RequestTemplate template) {
        String requestUrl = template.url();
        if (requestUrl.startsWith("http://") || requestUrl.startsWith("https://")) {
            return URI.create(requestUrl);
        }

        if (template.feignTarget() == null) {
            throw new IllegalStateException("Feign target URL is required to sign SES request");
        }

        String baseUrl = template.feignTarget().url();
        String fullUrl;
        if (baseUrl.endsWith("/") && requestUrl.startsWith("/")) {
            fullUrl = baseUrl.substring(0, baseUrl.length() - 1) + requestUrl;
        } else if (!baseUrl.endsWith("/") && !requestUrl.startsWith("/")) {
            fullUrl = baseUrl + "/" + requestUrl;
        } else {
            fullUrl = baseUrl + requestUrl;
        }
        return URI.create(fullUrl);
    }

    private String normalizePath(String rawPath) {
        if (rawPath == null || rawPath.isBlank()) {
            return "/";
        }
        return rawPath;
    }
}
